# Generated by Django 6.0.3 on 2026-03-08 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Numbersystem',
        ),
    ]
