# Generated by Django 6.0.3 on 2026-03-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_rename_question_numbersystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='numbersystem',
            name='correct_answer',
            field=models.CharField(default=2, max_length=1),
            preserve_default=False,
        ),
    ]
