# Generated by Django 6.0.3 on 2026-03-11 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_uploadedpdf_question_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedpdf',
            name='pdf_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploaded_pdfs/'),
            preserve_default=False,
        ),
    ]
