# Generated by Django 6.0.3 on 2026-03-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_topic_quizpdf_alter_question_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='question',
            name='source_pdf',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_pdfs/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topic'),
        ),
    ]
