# Generated by Django 6.0.3 on 2026-03-14 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_remove_question_pdf_file_question_source_pdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizpdf',
            name='topic',
        ),
        migrations.DeleteModel(
            name='UploadedPDF',
        ),
        migrations.DeleteModel(
            name='QuizPDF',
        ),
    ]
