# Generated by Django 6.0.3 on 2026-03-15 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_remove_quizpdf_topic_delete_uploadedpdf_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='source_pdf',
        ),
    ]
