# Generated by Django 6.0.3 on 2026-03-17 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_alter_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attempt',
            name='quiz',
        ),
        migrations.AddField(
            model_name='attempt',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.topic'),
        ),
    ]
