# Generated by Django 6.0.3 on 2026-03-17 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_remove_attempt_quiz_attempt_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attempt',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.topic'),
        ),
    ]
